### ISSUE TITLE
Is there a way to remove the padding within the editor?

### ISSUE THREAD

**Issue by evrimfeyyaz** [imnapo/react-native-cn-quill#36]
I tried setting `customStyles` to `["padding: 0"]`, but that didn't help. Any suggestions?

**Comment by imnapo** [comment]
All padding should be zero by default.
Could you please specify more details?
For `customStyles` Example: `[‘body { padding: 0;}’]`

**Comment by imnapo** [comment]
@evrimfeyyaz Please post your code here to be able to help you.

**Comment by evrimfeyyaz** [comment]
@imnapo We ended up using a different library as we were in a hurry, but I really like this library and I'm thinking that we might move to this in the future. If that happens and if I'm having the same issue at that time, I will update this issue. Thank you for being very considerate, I appreciate it!

**Comment by Robiullah2244** [comment]
@evrimfeyyaz which library you are using right now? Can you please share with me?

**Comment by evrimfeyyaz** [comment]
@Robiullah2244 I left that project long ago, but we were using this: https://github.com/wxik/react-native-rich-editor.

Keep in mind that, that project also has its issues and not perfect. IMO, this project has more potential.

**Comment by aldinoanggawan** [comment]
If there's anyone came across this, the padding is actually caused by these:
- https://github.com/imnapo/react-native-cn-quill/blob/master/src/utils/editor-utils.ts#L60-L62
- https://github.com/imnapo/react-native-cn-quill/blob/96b480977b24a937f4df331514f4338af6c8bdb2/src/constants/editor/quill_snow_css.ts#L43

There's a default padding of `12px 15px` in `quill_snow_css`

To get rid of this, we can add `customStyles={['<style>.ql-editor { padding: 0; }</style>']}`

Hope it helps 😄

**Comment by madsmeinertandersenITU** [comment]
@aldinoanggawan, I have really worked with any of this before, so where do I need to add the line customStyles={['<style>.ql-editor { padding: 0; }</style>']} to remove the padding? :)
